### Pytorch fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+cpu


### Creating tensors

In [21]:
# scaler - zero dimention tensor called scaler
scaler = torch.tensor(8)
print("Scaler:", scaler)
print("D-type:", type(scaler))
print("Dimentions:",scaler.ndim)
print("Item of the tensor:", scaler.item())

Scaler: tensor(8)
D-type: <class 'torch.Tensor'>
Dimentions: 0
Item of the tensor: 8


In [31]:
# vector -
vector = torch.tensor([1, 2])
print("Vector:", vector)

Vector: tensor([1, 2])


In [37]:
# number of dimentions
vector.ndim

1

In [38]:
# shape of the vector
vector.shape

torch.Size([2])

In [40]:
## matrix
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [42]:
# dimntions of the matrix
matrix.ndim

2

In [45]:
# shape of the matrix
matrix.shape

torch.Size([2, 2])

#### sclicing

In [58]:
matrix[0]

tensor([1, 2])

In [57]:
matrix[1]

tensor([3, 4])

In [50]:
matrix[0][0]

tensor(1)

In [56]:
matrix[0][1]

tensor(2)

In [53]:
matrix[1][0]

tensor(3)

In [55]:
matrix[1][1]

tensor(4)

### Random tensors

In [71]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5829, 0.6939, 0.4812, 0.4346],
        [0.7130, 0.5108, 0.6448, 0.8456],
        [0.5353, 0.9928, 0.0191, 0.5549]])

In [75]:
# creating a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.0726, 0.4111, 0.4252,  ..., 0.0338, 0.5118, 0.3311],
         [0.0974, 0.5545, 0.1399,  ..., 0.7068, 0.5164, 0.1045],
         [0.3314, 0.1685, 0.1371,  ..., 0.1306, 0.1562, 0.0827],
         ...,
         [0.0798, 0.1138, 0.3205,  ..., 0.5036, 0.7253, 0.2089],
         [0.3138, 0.5732, 0.9329,  ..., 0.2721, 0.6485, 0.8731],
         [0.5825, 0.9066, 0.9720,  ..., 0.8408, 0.3265, 0.3604]],

        [[0.6529, 0.1868, 0.8092,  ..., 0.1638, 0.3984, 0.2990],
         [0.2953, 0.9612, 0.5148,  ..., 0.5403, 0.9344, 0.6635],
         [0.2810, 0.0260, 0.3989,  ..., 0.0523, 0.6613, 0.2235],
         ...,
         [0.0384, 0.7375, 0.5321,  ..., 0.3339, 0.7261, 0.1778],
         [0.3132, 0.7666, 0.6451,  ..., 0.3466, 0.6488, 0.2955],
         [0.1349, 0.6026, 0.9008,  ..., 0.3850, 0.6680, 0.8422]],

        [[0.9042, 0.0524, 0.3668,  ..., 0.0646, 0.1310, 0.5606],
         [0.1792, 0.2638, 0.1938,  ..., 0.2212, 0.7041, 0.1941],
         [0.3671, 0.5596, 0.3868,  ..., 0.5331, 0.8254, 0.

In [78]:
# shape and dimention
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [83]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [84]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [87]:
zeros.ndim

2

In [88]:
zeros.shape

torch.Size([3, 4])

In [91]:
zeros.dtype

torch.float32

In [89]:
ones.ndim

2

In [90]:
ones.shape

torch.Size([3, 4])

In [92]:
ones.dtype

torch.float32

### Creating a arange of tensors and tensors-like

`Note: torch.range function is derprecated` 

In [102]:
# one to ten - start from one and last number it does not canclude
one_to_ten= torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
one_to_ten.shape

torch.Size([10])

In [99]:
one_to_ten.ndim

1

In [101]:
one_to_ten.dtype

torch.int64

In [110]:
# Another way to use arange
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
# user step with different number
torch.arange(start=0, end=20, step=5)

tensor([ 0,  5, 10, 15])

In [117]:
# Creating tensors like -  I have user one_to_ten tensor to create a nother zero_like_tensor
torch.zeros_like(one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right `datatype`
2. Tensors not right `shape`
3. Tensors not on the right `device`

In [130]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # defines tensors data type
                              device=None, # tensors on which device runnin on
                              requires_grad=False) #  whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [132]:
float_32_tensor.dtype

torch.float32

In [133]:
# Float 32 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16, # defines tensors data type
                              device=None, # tensors on which device runnin on
                              requires_grad=False) #  whether or not to track gradients with this tensors operations
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [137]:
# convert 32 bytes into 16 bytes
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [138]:
# operation with 16 bytes and 32 bytes of data type
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [141]:
# it woks with these bytes
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [142]:
float_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [143]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

In [147]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0661, 0.9537, 0.6657, 0.8114],
        [0.7626, 0.7220, 0.1688, 0.2217],
        [0.0589, 0.7160, 0.9868, 0.4764]])

#### Find out details about some tensor

In [153]:
# check date type
some_tensor.dtype

torch.float32

In [154]:
# check dimentions
some_tensor.ndim

2

In [155]:
# check device on which tensor is running on
some_tensor.device

device(type='cpu')

In [157]:
# tensor shape
some_tensor.shape

torch.Size([3, 4])

### Manipulating Tensors (tensor operations)

Tensor opertions include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [170]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [162]:
tensor +  10

tensor([11, 12, 13])

In [163]:
tensor * 10

tensor([10, 20, 30])

In [164]:
tensor - 10

tensor([-9, -8, -7])

In [165]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [172]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [173]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [174]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [175]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [176]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [177]:
torch.divide(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [178]:
torch.square(tensor)

tensor([1, 4, 9])

In [179]:
torch.sqrt(tensor)

tensor([1.0000, 1.4142, 1.7321])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

- Element-wise multiplication
- Matrix mutliplication (dot product)


In [182]:
print(tensor, "*", tensor)
print("Equal:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [184]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)