<a href="https://colab.research.google.com/github/Kamaljit12/pytorch-tutorial/blob/main/00_pytorch_fundamentals_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch fundamentals

In [1]:
# ! pip install torch pandas numpy matplotlib

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


### Creating tensors

In [3]:
# scaler - zero dimention tensor called scaler
scaler = torch.tensor(8)
print("Scaler:", scaler)
print("D-type:", type(scaler))
print("Dimentions:",scaler.ndim)
print("Item of the tensor:", scaler.item())

Scaler: tensor(8)
D-type: <class 'torch.Tensor'>
Dimentions: 0
Item of the tensor: 8


In [4]:
# vector -
vector = torch.tensor([1, 2])
print("Vector:", vector)

Vector: tensor([1, 2])


In [5]:
# number of dimentions
vector.ndim

1

In [6]:
# shape of the vector
vector.shape

torch.Size([2])

In [7]:
## matrix
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [8]:
# dimntions of the matrix
matrix.ndim

2

In [9]:
# shape of the matrix
matrix.shape

torch.Size([2, 2])

#### sclicing

In [10]:
matrix[0]

tensor([1, 2])

In [11]:
matrix[1]

tensor([3, 4])

In [12]:
matrix[0][0]

tensor(1)

In [13]:
matrix[0][1]

tensor(2)

In [14]:
matrix[1][0]

tensor(3)

In [15]:
matrix[1][1]

tensor(4)

### Random tensors

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6861, 0.6741, 0.6067, 0.8905],
        [0.5027, 0.5657, 0.3035, 0.9980],
        [0.4793, 0.8269, 0.6573, 0.9922]])

In [17]:
# creating a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.2472, 0.0982, 0.6034,  ..., 0.4010, 0.1853, 0.3386],
         [0.9927, 0.6936, 0.1083,  ..., 0.3900, 0.8441, 0.2142],
         [0.1798, 0.9998, 0.7987,  ..., 0.6421, 0.4518, 0.7788],
         ...,
         [0.0092, 0.1101, 0.1798,  ..., 0.7891, 0.3917, 0.1809],
         [0.2859, 0.8330, 0.7737,  ..., 0.1403, 0.3780, 0.0321],
         [0.4888, 0.2279, 0.0549,  ..., 0.5030, 0.0655, 0.7289]],

        [[0.1619, 0.9782, 0.6943,  ..., 0.6739, 0.6668, 0.3351],
         [0.7312, 0.4452, 0.0564,  ..., 0.1075, 0.5367, 0.9944],
         [0.3248, 0.6274, 0.0209,  ..., 0.3918, 0.6970, 0.4840],
         ...,
         [0.8668, 0.4073, 0.2176,  ..., 0.4470, 0.9091, 0.7911],
         [0.5543, 0.8556, 0.7524,  ..., 0.5961, 0.4352, 0.1886],
         [0.9201, 0.2801, 0.0396,  ..., 0.6517, 0.8822, 0.6818]],

        [[0.6854, 0.6236, 0.4715,  ..., 0.1957, 0.9752, 0.4903],
         [0.5302, 0.1586, 0.6580,  ..., 0.1387, 0.4339, 0.8794],
         [0.9666, 0.3028, 0.5202,  ..., 0.3433, 0.6797, 0.

In [18]:
# shape and dimention
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [19]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
zeros.ndim

2

In [22]:
zeros.shape

torch.Size([3, 4])

In [23]:
zeros.dtype

torch.float32

In [24]:
ones.ndim

2

In [25]:
ones.shape

torch.Size([3, 4])

In [26]:
ones.dtype

torch.float32

### Creating a arange of tensors and tensors-like

`Note: torch.range function is derprecated`

In [27]:
# one to ten - start from one and last number it does not canclude
one_to_ten= torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
one_to_ten.shape

torch.Size([10])

In [29]:
one_to_ten.ndim

1

In [30]:
one_to_ten.dtype

torch.int64

In [31]:
# Another way to use arange
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# user step with different number
torch.arange(start=0, end=20, step=5)

tensor([ 0,  5, 10, 15])

In [33]:
# Creating tensors like -  I have user one_to_ten tensor to create a nother zero_like_tensor
torch.zeros_like(one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right `datatype`
2. Tensors not right `shape`
3. Tensors not on the right `device`

In [34]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # defines tensors data type
                              device=None, # tensors on which device runnin on
                              requires_grad=False) #  whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
# Float 32 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16, # defines tensors data type
                              device=None, # tensors on which device runnin on
                              requires_grad=False) #  whether or not to track gradients with this tensors operations
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
# convert 32 bytes into 16 bytes
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
# operation with 16 bytes and 32 bytes of data type
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [39]:
# it woks with these bytes
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [40]:
float_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [41]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

In [42]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2924, 0.6546, 0.6490, 0.0950],
        [0.8264, 0.1541, 0.7457, 0.6976],
        [0.9316, 0.7010, 0.0992, 0.5943]])

#### Find out details about some tensor

In [43]:
# check date type
some_tensor.dtype

torch.float32

In [44]:
# check dimentions
some_tensor.ndim

2

In [45]:
# check device on which tensor is running on
some_tensor.device

device(type='cpu')

In [46]:
# tensor shape
some_tensor.shape

torch.Size([3, 4])

### Manipulating Tensors (tensor operations)

Tensor opertions include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [47]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [48]:
tensor +  10

tensor([11, 12, 13])

In [49]:
tensor * 10

tensor([10, 20, 30])

In [50]:
tensor - 10

tensor([-9, -8, -7])

In [51]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [52]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [53]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [54]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [55]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [56]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [57]:
torch.divide(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [58]:
torch.square(tensor)

tensor([1, 4, 9])

In [59]:
torch.sqrt(tensor)

tensor([1.0000, 1.4142, 1.7321])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

- Element-wise multiplication
- Matrix mutliplication (dot product)


In [60]:
print(tensor, "*", tensor)
print("Equal:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [61]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [62]:
tensor

tensor([1, 2, 3])

In [63]:
%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.72 µs
tensor(14)


In [64]:
%time
torch.matmul(tensor, tensor)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 6.91 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [65]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

In [66]:
# torch.matmul(tensor_A, tensor_B)

In [67]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [68]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [69]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [70]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [71]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [72]:
# create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [73]:
torch.min(x), torch.max(x)

(tensor(1), tensor(91))

In [74]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [75]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [76]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [77]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [78]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [79]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimum value occurs
x.argmax()

tensor(9)

In [80]:
x.argmin()

tensor(0)

In [81]:
torch.argmin(x)

tensor(0)

In [82]:
torch.argmax(x)

tensor(9)

In [83]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

In [84]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [85]:
x.shape

torch.Size([9])

In [86]:
x.reshape(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [87]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
# Change the view
x.view(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [89]:
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [90]:
z[:, 0]

tensor([1., 4., 7.])

In [91]:
z = z.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [92]:
# update the value
z[:, 0] = 5

In [93]:
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [94]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [95]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [96]:
x_stacked.shape

torch.Size([9, 4])

In [97]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [98]:
# remove one dimention from the tensor
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [99]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [112]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(224, 224, 3)
x_original.shape

torch.Size([224, 224, 3])

In [113]:
x_original.ndim

3

In [124]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permute = torch.permute(input = x_original, dims=(2, 0, 1)) # shifts axis 0->1, 1->2, 2->0
x_permute

tensor([[[0.4057, 0.4090, 0.7101,  ..., 0.1838, 0.0683, 0.9523],
         [0.8290, 0.0084, 0.8038,  ..., 0.9318, 0.3992, 0.2709],
         [0.6598, 0.9985, 0.1511,  ..., 0.4227, 0.8634, 0.0213],
         ...,
         [0.6640, 0.1928, 0.8137,  ..., 0.9150, 0.8468, 0.9436],
         [0.8664, 0.5698, 0.2258,  ..., 0.3310, 0.6628, 0.5690],
         [0.2496, 0.9949, 0.9231,  ..., 0.4953, 0.3131, 0.8632]],

        [[0.6327, 0.2075, 0.1579,  ..., 0.5299, 0.7705, 0.1027],
         [0.7342, 0.6131, 0.1551,  ..., 0.5074, 0.2482, 0.9697],
         [0.4121, 0.1484, 0.3231,  ..., 0.4901, 0.0962, 0.0600],
         ...,
         [0.9960, 0.0619, 0.5826,  ..., 0.8933, 0.6203, 0.2073],
         [0.8670, 0.4535, 0.7271,  ..., 0.2135, 0.4924, 0.3958],
         [0.0054, 0.8143, 0.4235,  ..., 0.6043, 0.7781, 0.1985]],

        [[0.4161, 0.1368, 0.0603,  ..., 0.4818, 0.1664, 0.2936],
         [0.8361, 0.2248, 0.9459,  ..., 0.6308, 0.5791, 0.0521],
         [0.0027, 0.6882, 0.5162,  ..., 0.1042, 0.6330, 0.

In [125]:
x_permute.shape

torch.Size([3, 224, 224])

In [130]:
x_original[0][0][0]

tensor(0.4057)

In [133]:
x_original[0, 0, 0]

tensor(0.4057)

In [135]:
x_original[0, 0, 0] = 728279

In [137]:
x_original[0, 0, 0], x_permute[0, 0, 0]

(tensor(728279.), tensor(728279.))

### **Indexing (selecting data from tensors)**

Indexing with PyTorch is similar to indexing with NumPy.

In [141]:
import torch

x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
torch.reshape(x, (1, 3, 3))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [161]:
x = x.reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [162]:
x[0][0]

tensor([1, 2, 3])

In [183]:
# Let's index on the middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [166]:
x[0, 0, 0]

tensor(1)

In [181]:
# Let's index on the most inner bracket (last dimension)
x, x[0, 1, 1]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor(5))

In [208]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [210]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [211]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [222]:
# Index on x to return 9
x[0, 2, 2], x[0][2][2]

(tensor(9), tensor(9))

In [228]:
# Index on x to return 3, 6, 9
x[:,:, 2]

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [251]:
# numpy to tensor
import numpy as np
import torch

x = np.arange(1., 8.)
x

array([1., 2., 3., 4., 5., 6., 7.])

In [252]:
type(x)

numpy.ndarray

In [253]:
x.shape, x.ndim

((7,), 1)

In [254]:
# convert numpy array to pytorch tensor
tensor = torch.from_numpy(x)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [255]:
type(tensor)

torch.Tensor

In [256]:
tensor.shape, tensor.ndim

(torch.Size([7]), 1)

In [257]:
x = x + 1
x, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [261]:
tensor = torch.ones(7)
numpy_array = tensor.numpy()

tensor, numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [262]:
tensor + 1, numpy_array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [266]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.5553, 0.2749, 0.9062, 0.8769],
        [0.2802, 0.0125, 0.3923, 0.1850],
        [0.7172, 0.0871, 0.8177, 0.9626]])
tensor([[0.2476, 0.1985, 0.9825, 0.9113],
        [0.5728, 0.5707, 0.9510, 0.3711],
        [0.3286, 0.7424, 0.9376, 0.9395]])


In [267]:
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [269]:
# Let's make some random but reproducible tensors
random_seed = 42

torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3, 4)


print(random_tensor_C)
print(random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [270]:
random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors and PyTorch objects on the GPUs (and making faster computations)

In [273]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [274]:
# check for GPU access with pytorch
import torch

torch.cuda.is_available()

False

In [1]:
!nvidia-smi

Sat Dec  6 08:10:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch

torch.cuda.is_available()

True

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [6]:
device

'cuda'

### 3. Putting tensors (and models) on the GPU

In [8]:
import torch

tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [10]:
# check tensor on device
tensor.device

device(type='cpu')

In [13]:
tensor.to(device)

tensor([1, 2, 3], device='cuda:0')

In [15]:
tensor = tensor.to(device)

tensor.device

device(type='cuda', index=0)

### Moving tensors back to the CPU

In [16]:
tensor.device

device(type='cuda', index=0)

In [17]:
# If tensor is on GPU, can't transform it to NumPy
tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [23]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_on_cpu = tensor.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [24]:
tensor_on_cpu.device

'cpu'

In [25]:
tensor.device

device(type='cuda', index=0)