<a href="https://colab.research.google.com/github/Kamaljit12/pytorch-tutorial/blob/main/00_pytorch_fundamentals_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch fundamentals

In [240]:
# ! pip install torch pandas numpy matplotlib

In [241]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


### Creating tensors

In [242]:
# scaler - zero dimention tensor called scaler
scaler = torch.tensor(8)
print("Scaler:", scaler)
print("D-type:", type(scaler))
print("Dimentions:",scaler.ndim)
print("Item of the tensor:", scaler.item())

Scaler: tensor(8)
D-type: <class 'torch.Tensor'>
Dimentions: 0
Item of the tensor: 8


In [243]:
# vector -
vector = torch.tensor([1, 2])
print("Vector:", vector)

Vector: tensor([1, 2])


In [244]:
# number of dimentions
vector.ndim

1

In [245]:
# shape of the vector
vector.shape

torch.Size([2])

In [246]:
## matrix
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [247]:
# dimntions of the matrix
matrix.ndim

2

In [248]:
# shape of the matrix
matrix.shape

torch.Size([2, 2])

#### sclicing

In [249]:
matrix[0]

tensor([1, 2])

In [250]:
matrix[1]

tensor([3, 4])

In [251]:
matrix[0][0]

tensor(1)

In [252]:
matrix[0][1]

tensor(2)

In [253]:
matrix[1][0]

tensor(3)

In [254]:
matrix[1][1]

tensor(4)

### Random tensors

In [255]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7378, 0.6402, 0.5896, 0.4688],
        [0.3005, 0.2904, 0.2151, 0.0282],
        [0.6848, 0.4056, 0.6975, 0.9424]])

In [256]:
# creating a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.4854, 0.6593, 0.8736,  ..., 0.5173, 0.6676, 0.6249],
         [0.1420, 0.4201, 0.0128,  ..., 0.0149, 0.4419, 0.1968],
         [0.9410, 0.4114, 0.9356,  ..., 0.3721, 0.0897, 0.4045],
         ...,
         [0.0837, 0.9819, 0.1043,  ..., 0.0781, 0.6713, 0.3074],
         [0.8448, 0.9597, 0.3448,  ..., 0.7804, 0.4403, 0.5519],
         [0.1968, 0.4270, 0.7919,  ..., 0.4082, 0.4694, 0.9737]],

        [[0.8353, 0.3950, 0.6782,  ..., 0.9053, 0.1697, 0.7636],
         [0.8862, 0.5913, 0.8100,  ..., 0.6145, 0.5662, 0.2524],
         [0.5698, 0.3785, 0.3296,  ..., 0.8070, 0.7072, 0.0336],
         ...,
         [0.2985, 0.7664, 0.0447,  ..., 0.9136, 0.4757, 0.2423],
         [0.8105, 0.5827, 0.1226,  ..., 0.1387, 0.7625, 0.8291],
         [0.1525, 0.5959, 0.6928,  ..., 0.8361, 0.9548, 0.8920]],

        [[0.6814, 0.6777, 0.1009,  ..., 0.4473, 0.7878, 0.5697],
         [0.0287, 0.7660, 0.3737,  ..., 0.5135, 0.7181, 0.8941],
         [0.9322, 0.7725, 0.8242,  ..., 0.2605, 0.9948, 0.

In [257]:
# shape and dimention
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [258]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [259]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [260]:
zeros.ndim

2

In [261]:
zeros.shape

torch.Size([3, 4])

In [262]:
zeros.dtype

torch.float32

In [263]:
ones.ndim

2

In [264]:
ones.shape

torch.Size([3, 4])

In [265]:
ones.dtype

torch.float32

### Creating a arange of tensors and tensors-like

`Note: torch.range function is derprecated`

In [266]:
# one to ten - start from one and last number it does not canclude
one_to_ten= torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [267]:
one_to_ten.shape

torch.Size([10])

In [268]:
one_to_ten.ndim

1

In [269]:
one_to_ten.dtype

torch.int64

In [270]:
# Another way to use arange
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [271]:
# user step with different number
torch.arange(start=0, end=20, step=5)

tensor([ 0,  5, 10, 15])

In [272]:
# Creating tensors like -  I have user one_to_ten tensor to create a nother zero_like_tensor
torch.zeros_like(one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right `datatype`
2. Tensors not right `shape`
3. Tensors not on the right `device`

In [273]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # defines tensors data type
                              device=None, # tensors on which device runnin on
                              requires_grad=False) #  whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [274]:
float_32_tensor.dtype

torch.float32

In [275]:
# Float 32 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16, # defines tensors data type
                              device=None, # tensors on which device runnin on
                              requires_grad=False) #  whether or not to track gradients with this tensors operations
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [276]:
# convert 32 bytes into 16 bytes
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [277]:
# operation with 16 bytes and 32 bytes of data type
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [278]:
# it woks with these bytes
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [279]:
float_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [280]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

In [281]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8375, 0.8206, 0.7954, 0.6946],
        [0.5398, 0.9238, 0.6328, 0.7773],
        [0.8137, 0.8321, 0.4066, 0.1881]])

#### Find out details about some tensor

In [282]:
# check date type
some_tensor.dtype

torch.float32

In [283]:
# check dimentions
some_tensor.ndim

2

In [284]:
# check device on which tensor is running on
some_tensor.device

device(type='cpu')

In [285]:
# tensor shape
some_tensor.shape

torch.Size([3, 4])

### Manipulating Tensors (tensor operations)

Tensor opertions include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [286]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [287]:
tensor +  10

tensor([11, 12, 13])

In [288]:
tensor * 10

tensor([10, 20, 30])

In [289]:
tensor - 10

tensor([-9, -8, -7])

In [290]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [291]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [292]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [293]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [294]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [295]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [296]:
torch.divide(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [297]:
torch.square(tensor)

tensor([1, 4, 9])

In [298]:
torch.sqrt(tensor)

tensor([1.0000, 1.4142, 1.7321])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

- Element-wise multiplication
- Matrix mutliplication (dot product)


In [299]:
print(tensor, "*", tensor)
print("Equal:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [300]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [301]:
tensor

tensor([1, 2, 3])

In [302]:
%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.25 µs
tensor(14)


In [303]:
%time
torch.matmul(tensor, tensor)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.01 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [304]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

In [305]:
# torch.matmul(tensor_A, tensor_B)

In [306]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [307]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [308]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [309]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [310]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [311]:
# create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [312]:
torch.min(x), torch.max(x)

(tensor(1), tensor(91))

In [313]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [314]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [315]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [316]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [317]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [318]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimum value occurs
x.argmax()

tensor(9)

In [319]:
x.argmin()

tensor(0)

In [320]:
torch.argmin(x)

tensor(0)

In [321]:
torch.argmax(x)

tensor(9)

In [322]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

In [323]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [324]:
x.shape

torch.Size([9])

In [325]:
x.reshape(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [326]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [327]:
# Change the view
x.view(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [328]:
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [329]:
z[:, 0]

tensor([1., 4., 7.])

In [330]:
z = z.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [331]:
# update the value
z[:, 0] = 5

In [332]:
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [336]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [337]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [338]:
x_stacked.shape

torch.Size([9, 4])

In [340]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [345]:
# remove one dimention from the tensor
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [346]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))